services:
  app:
    image: ghcr.io/10h30/markdownblog:latest
    container_name: markdownblog
    restart: always
    volumes:
      - ./storage:/var/www/storage
      - ./database/database.sqlite:/var/www/database/database.sqlite
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/storage/database.sqlite
    depends_on:
      - caddy

  caddy:
    image: caddy:latest
    container_name: caddy_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./storage:/var/www/html/storage
      - caddy_data:/data
      - caddy_config:/config


volumes:
  caddy_data:
  caddy_config:
